# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', 'ssc_0001_shift_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='This shift is not yet publicly visible. It has to be opened manually'),
        ),
    ]
